#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Mar 27 15:57:09 MDT 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a2bde4f5fe344452bc233cef09acfa17 --incr --debug typical --relax --mt 8 -generic_top "TEXT_MEMORY_FILENAME=final_text.mem" -generic_top "DATA_MEMORY_FILENAME=final_data.mem" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot riscv_final_tb_behav xil_defaultlib.riscv_final_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto a2bde4f5fe344452bc233cef09acfa17 --incr --debug typical --relax --mt 8 -generic_top "TEXT_MEMORY_FILENAME=final_text.mem" -generic_top "DATA_MEMORY_FILENAME=final_data.mem" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot riscv_final_tb_behav xil_defaultlib.riscv_final_tb xil_defaultlib.glbl -log elaborate.log

